SELECT 
L_RETURNFLAG,
L_LINESTATUS,
SUM(L_QUANTITY) AS SUM_QTY,
SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE,
AVG(L_QUANTITY) AS AVG_QTY,
AVG(L_EXTENDEDPRICE) AS AVG_PRICE,
AVG(L_DISCOUNT) AS AVG_DISC,
COUNT(*) AS COUNT_ORDER
FROM 
LINEITEM
WHERE 
L_SHIPDATE <= '1998-09-26' 
GROUP BY 
L_RETURNFLAG,
L_LINESTATUS
ORDER BY L_RETURNFLAG, L_LINESTATUS;
