#ifndef ZLIB_PREFIX_H
#define ZLIB_PREFIX_H
/* all linked symbols */
#define _dist_code            innobase_z__dist_code
#define _length_code          innobase_z__length_code
#define _tr_align             innobase_z__tr_align
#define _tr_flush_block       innobase_z__tr_flush_block
#define _tr_init              innobase_z__tr_init
#define _tr_stored_block      innobase_z__tr_stored_block
#define _tr_tally             innobase_z__tr_tally
#define adler32               innobase_z_adler32
#define adler32_combine64     innobase_z_adler32_combine64
#define compress              innobase_z_compress
#define compress2             innobase_z_compress2
#define compressBound         innobase_z_compressBound
#define crc32                 innobase_z_crc32
#define crc32_combine64       innobase_z_crc32_combine64
#define deflate               innobase_z_deflate
#define deflateBound          innobase_z_deflateBound
#define deflateCopy           innobase_z_deflateCopy
#define deflateEnd            innobase_z_deflateEnd
#define deflateInit2_         innobase_z_deflateInit2_
#define deflateInit_          innobase_z_deflateInit_
#define deflateParams         innobase_z_deflateParams
#define deflatePrime          innobase_z_deflatePrime
#define deflateReset          innobase_z_deflateReset
#define deflateSetDictionary  innobase_z_deflateSetDictionary
#define deflateSetHeader      innobase_z_deflateSetHeader
#define deflateTune           innobase_z_deflateTune
#define deflate_copyright     innobase_z_deflate_copyright
#define get_crc_table         innobase_z_get_crc_table
#define gz_error              innobase_z_gz_error
#define gz_intmax             innobase_z_gz_intmax
#define gz_strwinerror        innobase_z_gz_strwinerror
#define gzbuffer              innobase_z_gzbuffer
#define gzclearerr            innobase_z_gzclearerr
#define gzclose               innobase_z_gzclose
#define gzclose_r             innobase_z_gzclose_r
#define gzclose_w             innobase_z_gzclose_w
#define gzdirect              innobase_z_gzdirect
#define gzdopen               innobase_z_gzdopen
#define gzeof                 innobase_z_gzeof
#define gzerror               innobase_z_gzerror
#define gzflush               innobase_z_gzflush
#define gzgetc                innobase_z_gzgetc
#define gzgets                innobase_z_gzgets
#define gzoffset64            innobase_z_gzoffset64
#define gzopen64              innobase_z_gzopen64
#define gzprintf              innobase_z_gzprintf
#define gzputc                innobase_z_gzputc
#define gzputs                innobase_z_gzputs
#define gzread                innobase_z_gzread
#define gzrewind              innobase_z_gzrewind
#define gzseek64              innobase_z_gzseek64
#define gzsetparams           innobase_z_gzsetparams
#define gztell64              innobase_z_gztell64
#define gzungetc              innobase_z_gzungetc
#define gzwrite               innobase_z_gzwrite
#define inflate               innobase_z_inflate
#define inflateBack           innobase_z_inflateBack
#define inflateBackEnd        innobase_z_inflateBackEnd
#define inflateBackInit_      innobase_z_inflateBackInit_
#define inflateCopy           innobase_z_inflateCopy
#define inflateEnd            innobase_z_inflateEnd
#define inflateGetHeader      innobase_z_inflateGetHeader
#define inflateInit2_         innobase_z_inflateInit2_
#define inflateInit_          innobase_z_inflateInit_
#define inflateMark           innobase_z_inflateMark
#define inflatePrime          innobase_z_inflatePrime
#define inflateReset          innobase_z_inflateReset
#define inflateReset2         innobase_z_inflateReset2
#define inflateSetDictionary  innobase_z_inflateSetDictionary
#define inflateSync           innobase_z_inflateSync
#define inflateSyncPoint      innobase_z_inflateSyncPoint
#define inflateUndermine      innobase_z_inflateUndermine
#define inflate_copyright     innobase_z_inflate_copyright
#define inflate_fast          innobase_z_inflate_fast
#define inflate_table         innobase_z_inflate_table
#define uncompress            innobase_z_uncompress
#define zError                innobase_z_zError
#define zcalloc               innobase_z_zcalloc
#define zcfree                innobase_z_zcfree
#define zlibCompileFlags      innobase_z_zlibCompileFlags
#define zlibVersion           innobase_z_zlibVersion

/* all zlib typedefs in zlib.h and zconf.h */
#define Byte                  innobase_z_Byte
#define Bytef                 innobase_z_Bytef
#define alloc_func            innobase_z_alloc_func
#define charf                 innobase_z_charf
#define free_func             innobase_z_free_func
#define gzFile                innobase_z_gzFile
#define gz_header             innobase_z_gz_header
#define gz_headerp            innobase_z_gz_headerp
#define in_func               innobase_z_in_func
#define intf                  innobase_z_intf
#define out_func              innobase_z_out_func
#define uInt                  innobase_z_uInt
#define uIntf                 innobase_z_uIntf
#define uLong                 innobase_z_uLong
#define uLongf                innobase_z_uLongf
#define voidp                 innobase_z_voidp
#define voidpc                innobase_z_voidpc
#define voidpf                innobase_z_voidpf

/* all zlib structs in zlib.h and zconf.h */
#define gz_header_s           innobase_z_gz_header_s
#define internal_state        innobase_z_internal_state

#endif /* ZLIB_PREFIX_H */
