<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'FacebookArcanistConfiguration' => 'arcanist/FacebookArcanistConfiguration.php',
    'FacebookBuildServer' => 'unit/FacebookBuildServer.php',
    'FacebookDiffCreatedListener' => 'unit/FacebookDiffCreatedListener.php',
    'FacebookFbcodeUnitTestEngine' => 'unit/FacebookMysqlUnitTestEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'FacebookArcanistConfiguration' => 'ArcanistConfiguration',
    'FacebookDiffCreatedListener' => 'PhutilEventListener',
    'FacebookFbcodeUnitTestEngine' => 'ArcanistBaseUnitTestEngine',
  ),
));
