<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'FacebookMySQLArcanistConfiguration' => 'arcanist/FacebookMySQLArcanistConfiguration.php',
    'FacebookMySQLCppLinter' => 'lint/linter/FacebookMySQLCppLinter.php',
    'FacebookMySQLDiffCreatedListener' => 'unit/FacebookMySQLDiffCreatedListener.php',
    'FacebookMySQLLintEngine' => 'lint/FacebookMySQLLintEngine.php',
    'FacebookMySQLLinter' => 'lint/linter/FacebookMySQLLinter.php',
    'FacebookMySQLUnitTestEngine' => 'unit/FacebookMySQLUnitTestEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'FacebookMySQLArcanistConfiguration' => 'ArcanistConfiguration',
    'FacebookMySQLCppLinter' => 'ArcanistLinter',
    'FacebookMySQLDiffCreatedListener' => 'PhutilEventListener',
    'FacebookMySQLLintEngine' => 'ArcanistLintEngine',
    'FacebookMySQLLinter' => 'ArcanistLinter',
    'FacebookMySQLUnitTestEngine' => 'ArcanistBaseUnitTestEngine',
  ),
));
