#! /bin/sh
#
#/*******************************************************************************
#*  Script Name:    pscollect
#*  Date Created:   2009.01.27
#*  Author:         Stephen Cargile
#*  Purpose:        capture system activity every x seconds
#*
#******************************************************************************/
#
cd /var/log/prat/ps
    if [ ! -d /var/log/prat/ps/`date +%m%d%y` ]
    then 
	mkdir `date +%m%d%y`
    else
	cd `date +%m%d%y`
    	hostname -s > ps_`date +%H%M`.txt
	date >> ps_`date +%H%M`.txt
	/bin/ps -leaf >> ps_`date +%H%M`.txt   
    fi

#    if [ -f /usr/bin/pstree ]
#    then
#	/usr/bin/pstree -G > pstree_`date +%R`.txt
#    else
#	echo "binary /usr/bin/pstree not installed." > pstree_`date +%R`.txt
#    fi

# End of script
